import { Container } from "../src/styles/FraseIA.ts";
import React, { useState, useEffect } from "react";

export function FraseIA() {
  const ListaDeFrases = [
    "Smart TV, reviva suas noites de entretenimento consertando sua TV conosco.",
    "Smart TV, não deixe sua TV estragar seu dia. Conserte agora!",
    "Smart TV, conserte sua TV e volte a desfrutar dos seus programas favoritos.",
    "Smart TV, a tela preta não precisa ser o fim. Nós resolvemos!",
    "Smart TV, sua TV merece um reparo de qualidade. Confie em nós!",
    "Smart TV, recupere a qualidade de imagem com nosso serviço de conserto.",
    "Smart TV, transforme problemas em soluções com nosso conserto especializado.",
    "Smart TV, não perca mais tempo! Conserte sua TV hoje.",
    "Smart TV, volte a ver a vida em alta definição. Conserte sua TV!",
    "Smart TV, problemas com a TV? Nós temos a solução.",
    "Smart TV, repare sua TV com quem entende do assunto.",
    "Smart TV, seu entretenimento de volta com nosso conserto de TV.",
    "Smart TV, conserte sua TV e volte a curtir seus filmes favoritos.",
    "Smart TV, tecnologia em boas mãos. Traga sua TV para conserto!",
    "Smart TV, resolva seu problema de TV com um simples conserto.",
    "Smart TV, seu entretenimento merece o melhor. Conserte sua TV conosco.",
    "Smart TV, seu programa favorito está esperando. Conserte sua TV!",
    "Smart TV, repare sua TV e volte ao seu entretenimento.",
    "Smart TV, conserto de TV rápido e confiável é aqui.",
    "Smart TV, não deixe um problema técnico acabar com sua diversão.",
    "Smart TV, a tela perfeita está a um conserto de distância.",
    "Smart TV, volte a ver o mundo em cores vivas. Conserte sua TV.",
    "Smart TV, conserte sua TV e evite comprar uma nova.",
    "Smart TV, seu show favorito merece ser visto em uma TV funcionando!",
    "Smart TV, consertar sua TV é mais rápido do que você pensa.",
    "Smart TV, traga sua TV para conserto e não perca nenhum jogo.",
    "Smart TV, recupere a qualidade do som e da imagem com nosso serviço.",
    "Smart TV, seu lar merece uma TV perfeita. Conserte agora!",
    "Smart TV, problemas de TV? Conserte hoje e aproveite amanhã.",
    "Smart TV, sua TV funcionando como nova novamente!",
    "Smart TV, conserto de TV fácil e sem complicações.",
    "Smart TV, assistir TV deve ser prazeroso, não problemático. Conserte já!",
    "Smart TV, não deixe sua TV parada. Conserte hoje mesmo.",
    "Smart TV, volte a maratonar suas séries favoritas sem interrupções!",
    "Smart TV, conserte sua TV e aproveite noites de cinema em casa.",
    "Smart TV, seu entretenimento, restaurado com nosso conserto.",
    "Smart TV, conserte sua TV antes do próximo grande jogo.",
    "Smart TV, conserte sua TV e veja a diferença!",
    "Smart TV, seu entretenimento não pode esperar. Conserte sua TV hoje.",
    "Smart TV, repare sua TV e reviva a magia da imagem perfeita.",
    "Smart TV, assistir TV com qualidade? Conserte conosco!",
    "Smart TV, seu entretenimento merece um conserto de qualidade.",
    "Smart TV, conserte sua TV e não perca nenhum detalhe.",
    "Smart TV, volte a assistir seus programas sem interrupções.",
    "Smart TV, a TV perfeita está a um conserto de distância.",
    "Smart TV, não troque, conserte! Economize com nosso serviço.",
    "Smart TV, problemas técnicos? Conserte sua TV rapidamente!",
    "Smart TV, sua TV em boas mãos com nossos técnicos.",
    "Smart TV, conserte sua TV e recupere a qualidade de imagem.",
    "Smart TV, traga sua TV para conserto e veja a diferença!",
    "Smart TV, seu entretenimento de volta com um simples conserto.",
    "Smart TV, assistir TV nunca foi tão bom. Conserte a sua!",
    "Smart TV, volte a desfrutar da melhor qualidade de imagem.",
    "Smart TV, recupere o prazer de assistir TV com nosso conserto.",
    "Smart TV, sua TV merece o melhor. Conserte conosco!",
    "Smart TV, solução rápida e eficaz para sua TV.",
    "Smart TV, conserte sua TV e volte a maratonar suas séries.",
    "Smart TV, seu filme favorito está esperando. Conserte sua TV!",
    "Smart TV, não perca mais tempo. Conserte sua TV hoje.",
    "Smart TV, tecnologia e entretenimento restaurados com nosso conserto.",
    "Smart TV, conserte sua TV e aproveite noites de filmes.",
    "Smart TV, volte a curtir sua TV sem problemas.",
    "Smart TV, conserto de TV rápido e confiável, do jeito que você precisa.",
    "Smart TV, recupere o som e a imagem perfeitos com nosso conserto.",
    "Smart TV, sua TV funcionando perfeitamente, garantido!",
    "Smart TV, conserte sua TV e veja a diferença na qualidade.",
    "Smart TV, seu entretenimento não pode esperar. Conserte já!",
    "Smart TV, volte a aproveitar seu tempo livre com nossa ajuda.",
    "Smart TV, seu programa favorito em alta qualidade de novo.",
    "Smart TV, conserte sua TV e não perca mais nenhum detalhe.",
    "Smart TV, seu entretenimento está seguro com nosso conserto.",
    "Smart TV, TV funcionando como nova em pouco tempo.",
    "Smart TV, problemas de TV? Nós cuidamos de tudo.",
    "Smart TV, sua TV merece o melhor tratamento. Conserte aqui!",
    "Smart TV, recupere a qualidade da imagem com nosso serviço.",
    "Smart TV, conserte sua TV e veja a vida em HD!",
    "Smart TV, não perca mais nenhum episódio. Conserte sua TV hoje.",
    "Smart TV, tecnologia em boas mãos. Conserte sua TV conosco.",
    "Smart TV, conserte sua TV e volte a curtir seu entretenimento.",
    "Smart TV, imagem perfeita novamente com nosso conserto.",
    "Smart TV, assistir TV deve ser um prazer, não um problema.",
    "Smart TV, conserte sua TV e recupere o prazer de assistir.",
    "Smart TV, volte a ver seus programas favoritos sem problemas.",
    "Smart TV, aproveite a melhor qualidade de imagem de novo.",
    "Smart TV, tela preta? Não se preocupe, nós resolvemos!",
    "Smart TV, volte a assistir TV com imagem e som perfeitos.",
    "Smart TV, conserte sua TV e evite comprar uma nova.",
    "Smart TV, seu entretenimento restaurado com nosso conserto de TV.",
    "Smart TV, recupere a imagem perfeita com nosso serviço.",
    "Smart TV, sua TV merece o melhor cuidado. Conserte conosco!",
    "Smart TV, repare sua TV e aproveite cada detalhe da imagem.",
    "Smart TV, conserte sua TV e não perca nenhum momento.",
    "Smart TV, assistir TV deve ser prazeroso. Conserte hoje!",
    "Smart TV, volte a curtir sua TV sem preocupações.",
    "Smart TV, conserto rápido para sua TV, do jeito que você precisa.",
    "Smart TV, recupere o prazer de assistir TV com nosso serviço.",
    "Smart TV, sua TV funcionando perfeitamente, garantido!",
    "Smart TV, sua TV merece o melhor cuidado. Conserte conosco!",
    "Smart TV, conserte sua TV e veja a diferença na qualidade.",
    "Smart TV, tela perfeita de novo com nosso conserto especializado.",
  ];

  const [fraseIndex, setFraseIndex] = useState(0);

  function randomchange() {
    const random = Math.floor(Math.random() * ListaDeFrases.length);
    setFraseIndex(random);
  }
  useEffect(() => {
    const interval = setInterval(randomchange, 8000);
    return () => clearInterval(interval);
  }, []);

  return <Container>{ListaDeFrases[fraseIndex]}</Container>;
}
